language: node_js

node_js:
    - "8"

cache:
    directories:
        - "node_modules"

branches:
    only:
        - master

before_install:
    - npm i -g npm@latest
    - gem install bundler

install:
    - npm install
    - bundle update listen

script:
    - npm run test

after_success:
    - npm run build:prod