language: node_js

node_js:
    - "8"

cache:
    directories:
      - "node_modules"

before_install:
    - npm i -g npm@latest

install:
    - npm install
    - bundle install --path vendor/bundle

script:
    - npm run test

after_success:
    - npm run build:prod